# Generated by Django 3.0.7 on 2020-06-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('id', models.CharField(blank=True, max_length=18, null=True)),
            ],
            options={
                'db_table': 'person_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'register',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftInfo',
            fields=[
                ('shift_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('start', models.TextField()),
                ('end', models.TextField()),
                ('empty_ticket', models.IntegerField()),
                ('risk_level', models.IntegerField()),
            ],
            options={
                'db_table': 'shift_info',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='search',
            name='admin_id1',
        ),
        migrations.RemoveField(
            model_name='search',
            name='user_id1',
        ),
        migrations.RemoveField(
            model_name='send',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='send',
            name='record',
        ),
        migrations.RemoveField(
            model_name='submitrecord',
            name='record_id1',
        ),
        migrations.RemoveField(
            model_name='submitrecord',
            name='user_id2',
        ),
        migrations.DeleteModel(
            name='Admins',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.DeleteModel(
            name='Send',
        ),
        migrations.DeleteModel(
            name='SubmitRecord',
        ),
        migrations.DeleteModel(
            name='UserRecord',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
